Repository gomingout-project/web, pull requests merged in 2021-12, with the labels that each got.

#15 [style] 홈 화면 디자인 변경
  components/atoms/Icon/Search.tsx
  components/atoms/Span.tsx
  components/atoms/TextArea.tsx
  components/atoms/Title.tsx
  components/organisms/community/BoardLoading.tsx
  components/organisms/community/PostItem.tsx
  components/organisms/community/PostList.tsx
  components/templates/CommunityTemplate.tsx
  styles/color.ts
  styles/theme.ts
Labels: type: style, priority: high

#17 feat(bottom bar): make bottom bar
  components/atoms/Icon/Kakao.tsx
  components/atoms/Icon/Mypage.tsx
  components/atoms/Icon/WriteButton.tsx
  components/atoms/Icon/index.ts
  components/organisms/community/BottomNav.tsx
  components/organisms/community/index.ts
  components/templates/CommunityTemplate.tsx
  package-lock.json
  tsconfig.json
Labels: type: feat, status: blocked, priority: low

#16 feat : feed detail page
  components/atoms/Icon/Back.tsx
  components/atoms/Icon/More.tsx
  components/atoms/Icon/index.ts
  components/organisms/community/PostItem.tsx
  components/organisms/community/PostList.tsx
  components/templates/DetailPostTemplate.tsx
  components/templates/index.ts
  pages/community/detail.tsx
  styles/color.ts
Labels: type: feat, status: pending, priority: medium

#23 Feat/feed detail
  components/atoms/Icon/Back.tsx
  components/atoms/Icon/More.tsx
  components/atoms/Icon/index.ts
  components/organisms/community/PostItem.tsx
  components/organisms/community/PostList.tsx
  components/templates/DetailPostTemplate.tsx
  components/templates/index.ts
  pages/community/detail.tsx
  pages/community/detail/[postId]/index.tsx
  styles/color.ts
Labels: type: feat, status: pending

#21 [feat] category 기능 개발
  components/atoms/Icon/ArrowDown.tsx
  components/atoms/Icon/index.ts
  components/organisms/community/Category.tsx
  components/organisms/community/index.ts
  components/templates/CommunityTemplate.tsx
  constants/index.ts
  styles/color.ts
  utils/index.ts
  utils/useUrlParams.ts
Labels: type: feat, status: pending, priority: high

#24 [fix](detailPost): 이미지 미출력 이슈
  components/templates/DetailPostTemplate.tsx
Labels: type: fix, status: pending

#26 fix(intro): intro 페이지 디자인 수정
  components/templates/LoginTemplate.tsx
Labels: type: fix, status: pending, priority: high

#25 [feat]하단 바 + 툴팁 추가
  components/atoms/Icon/Home.tsx
  components/atoms/Icon/Mypage.tsx
  components/atoms/Icon/WriteIcon.tsx
  components/atoms/Icon/index.ts
  components/molcules/ToolTip.tsx
  components/molcules/index.ts
  components/organisms/common/BottomNav.tsx
  components/organisms/common/index.ts
  components/organisms/community/index.ts
  components/organisms/index.ts
  components/templates/CommunityTemplate.tsx
Labels: type: feat, status: pending, status: blocked, priority: medium
