Repository gomingout-project/web, pull requests merged in 2022-01, with the labels that each got.

#28 [feat] 앱처럼 보이기 위해 페이지 전환시 애니매이션 넣기
  components/molcules/PageAnimation.tsx
  components/molcules/index.ts
  package.json
  pages/_app.tsx
  pages/community/detail.tsx
  pages/community/detail/[postId]/index.tsx
  yarn.lock
Labels: type: feat, status: pending, priority: high

#31 [feat] app permission 관련 feature 추가
  components/atoms/Icon/Camera.tsx
  components/atoms/Icon/Folder.tsx
  components/atoms/Icon/index.ts
  components/atoms/Title.tsx
  components/molcules/Popup.tsx
  components/organisms/common/ATTPermissionRequestPopup.tsx
  components/organisms/common/PhotoPermissionBlockedPopup.tsx
  components/organisms/common/PhotoPermissionRequestPopup.tsx
  components/organisms/common/index.ts
  components/organisms/community/PostItem.tsx
  components/organisms/new/SelectCategory.tsx
  components/templates/LoginTemplate.tsx
  components/templates/NewPostTemplate.tsx
  utils/device.ts
Labels: type: feat, status: pending, priority: medium

#33 test: jest 설정
  .babelrc
  jest.config.js
  jest.setup.ts
  package-lock.json
  package.json
  yarn.lock
Labels: status: pending, type: test

#34 Feature/notification
  api/notification/hook.ts
  api/notification/index.ts
  api/notification/interface.ts
  components/organisms/common/BottomNav.tsx
  components/organisms/index.ts
  components/organisms/notification/NotificationItem.tsx
  components/organisms/notification/NotificationList.tsx
  components/organisms/notification/NotificationLoading.tsx
  components/organisms/notification/index.ts
  components/templates/CommunityTemplate.tsx
  components/templates/NotificationTemplate.tsx
  components/templates/index.ts
  constants/index.ts
  pages/notification/index.tsx
  styles/theme.ts
Labels: type: feat, priority: medium

#35 fix: 알림 로딩컴포넌트 내 map 메서드 key 추가
  components/organisms/notification/NotificationLoading.tsx
Labels: type: fix, status: pending

#36 [feat] ATT + Notification 권한 설정 팝업 추가
  components/atoms/Icon/Bell.tsx
  components/atoms/Icon/Loaction.tsx
  components/atoms/Icon/index.ts
  components/organisms/common/ATTPermissionRequestPopup.tsx
  components/templates/LoginTemplate.tsx
  pages/_app.tsx
  provider/AppAuthor.tsx
Labels: type: feat, status: pending, priority: medium
